---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-trident.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: O Astra Trident segue uma cadência de lançamento trimestral, entregando quatro grandes lançamentos todos os anos. Cada nova versão é construída sobre as versões anteriores, fornecendo novos recursos e melhorias de desempenho, bem como correções de bugs e melhorias. Recomendamos que você atualize pelo menos uma vez por ano para aproveitar os novos recursos do Astra Trident. 
---
= Atualizar o Astra Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Astra Trident segue uma cadência de lançamento trimestral, entregando quatro grandes lançamentos todos os anos. Cada nova versão é construída sobre as versões anteriores, fornecendo novos recursos e melhorias de desempenho, bem como correções de bugs e melhorias. Recomendamos que você atualize pelo menos uma vez por ano para aproveitar os novos recursos do Astra Trident.



== Selecione uma versão

As versões do Astra Trident seguem uma convenção de nomenclatura baseada em data `YY.MM`, onde "YY" é os últimos dois dígitos do ano e "MM" é o mês. Os lançamentos de ponto seguem uma `YY.MM.X` convenção, onde "X" é o nível de patch. Você selecionará a versão para a qual atualizar com base na versão da qual você está atualizando.

* Você pode fazer uma atualização direta para qualquer versão de destino que esteja dentro de uma janela de quatro versões da versão instalada. Por exemplo, você pode atualizar para 23,01 a partir de 22,01 (incluindo quaisquer lançamentos de pontos, como 22.01.1) diretamente.
* Se você tiver uma versão anterior, você deve executar uma atualização em várias etapas usando a documentação da respetiva versão para obter instruções específicas. Isso requer que você primeiro atualize para a versão mais recente que se encaixa na janela de quatro versões. Por exemplo, se você estiver executando o 18,07 e quiser atualizar para a versão 20,07, siga o processo de atualização em várias etapas conforme indicado abaixo:
+
.. Primeiro upgrade de 18,07 para 19,07.
.. Em seguida, atualize de 19,07 para 20,07.




[WARNING]
====
* Todas as atualizações para as versões 19,04 e anteriores exigem a migração dos metadados do Astra Trident próprios `etcd` para objetos CRD. Verifique a documentação da versão para entender como a atualização funciona.
* Ao atualizar, é importante que você forneça `parameter.fsType` o `StorageClasses` Astra Trident usado. Você pode excluir e recriar `StorageClasses` sem interromper volumes pré-existentes. Este é um ** requisito** para impor contextos https://kubernetes.io/docs/tasks/configure-pod-container/security-context/[security para volumes SAN. O diretório https://github.com/NetApp https://github.com/NetApp/Trident Trident/tree/master/Trident Trident-installer/sample-input[sample input] contém exemplos, como https://github.com/NetApp/Trident/blob/master/Trident-installer/sample-input/storage-class-samples/storage-class-[`storage-class-bronze-default.yaml`basic[`storage-class-basic.yaml.templ` Para obter mais informações, link:../trident-rn.html["Problemas conhecidos"]consulte .


====


== Selecione uma opção de atualização

Há duas opções para atualizar o Astra Trident. Geralmente, você usará a mesma opção usada para a instalação inicial, no entanto, você pode link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["mova entre os métodos de instalação"].

* link:upgrade-operator.html["Atualize usando o operador Trident"]
* 



WARNING: O CSI volume Snapshots agora é um recurso que é o GA, começando com o Kubernetes 1,20. Ao atualizar o Astra Trident, todos os CRS e CRDs de instantâneo alfa anteriores (classes de instantâneo de volume, instantâneos de volume e conteúdo de instantâneo de volume) devem ser removidos antes que a atualização seja executada.  https://netapp.io/2020/01/30/alpha-to-beta-snapshots/["este blog"^]Consulte para compreender os passos envolvidos na migração de instantâneos alfa para a especificação beta/GA.



== Alterações ao operador

O lançamento de 21,01 do Astra Trident introduz algumas mudanças importantes na arquitetura do operador, nomeadamente as seguintes:

* O operador está agora *com escopo de cluster*. Instâncias anteriores do operador Trident (versões 20,04 a 20,10) eram *com escopo de namespace*. Um operador com escopo de cluster é vantajoso pelas seguintes razões:
+
** Responsabilidade dos recursos: A operadora agora gerencia recursos associados à instalação do Astra Trident no nível do cluster. Como parte da instalação do Astra Trident, o operador cria e mantém vários recursos `ownerReferences` usando o . Manter `ownerReferences` recursos com escopo de cluster pode lançar erros em certos distribuidores do Kubernetes, como o OpenShift. Isso é atenuado com um operador com escopo de cluster. Para auto-cura e correção de recursos do Trident, este é um requisito essencial.
** Limpeza durante a desinstalação: Uma remoção completa do Astra Trident exigiria que todos os recursos associados fossem excluídos. Um operador com escopo de namespace pode ter problemas com a remoção de recursos com escopo de cluster (como o clusterRole, ClusterRoleBinding e PodSecurityPolicy) e levar a uma limpeza incompleta. Um operador com escopo de cluster elimina esse problema. Os usuários podem desinstalar completamente o Astra Trident e instalar novamente, se necessário.


* `TridentProvisioner` Agora é substituído pelo `TridentOrchestrator` como recurso personalizado usado para instalar e gerenciar o Astra Trident. Além disso, um novo campo é introduzido à `TridentOrchestrator` especificação. Os usuários podem especificar que o namespace Trident deve ser instalado/atualizado usando o `spec.namespace` campo. Você pode dar uma olhada em um exemplo https://github.com/NetApp/trident/blob/stable/v21.01/deploy/crds/tridentorchestrator_cr.yaml["aqui"^].

